services:  
  postgres_service:
    image: ${POSTGRES_IMAGE}
    container_name: postgres_container
    environment: 
      POSTGRES_DB: ${POSTGRES_SOURCE_DB} 
      POSTGRES_USER: ${POSTGRES_SOURCE_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_SOURCE_PASSWORD}
    env_file: .env
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"          # Debezium üçün mütləq
      - "-c"
      - "max_replication_slots=5"
      - "-c"
      - "max_wal_senders=5"
    ports:
      - "5433:5432"
    volumes:
      - source_pg_data_DebeziumCDC:/var/lib/postgresql/data
      - ./sql/init-source.sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_SOURCE_USER} -d ${POSTGRES_SOURCE_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - networkDebeziumCDC
    restart: always
  

volumes:
  source_pg_data_DebeziumCDC:
    name: DebeziumCDC_project3_sourceData

networks:
  networkDebeziumCDC:
    name: networkDebeziumCDC_project3
    external: true